name: Weekly Risk Prediction

on:
  schedule:
    - cron: '0 6 * * 1'  # every Monday at 6 AM UTC
  workflow_dispatch:     # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run prediction script
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          KEY_JSON: ${{ secrets.KEY_JSON }}
        run: python predict_and_log.py
